
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package br.udesc.ads.ponto.services.leitoraponto;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-06-10T19:55:09.374-03:00
 * Generated source version: 2.7.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "LeitoraPontoService",
                      portName = "LeitoraPontoServicePort",
                      targetNamespace = "http://leitoraponto.services.ponto.ads.udesc.br/",
                      wsdlLocation = "http://localhost:8080/leitora/services/LeitoraPontoServicePort?wsdl",
                      endpointInterface = "br.udesc.ads.ponto.services.leitoraponto.LeitoraPontoService")
                      
public class LeitoraPontoServiceImpl implements LeitoraPontoService {

    private static final Logger LOG = Logger.getLogger(LeitoraPontoServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see br.udesc.ads.ponto.services.leitoraponto.LeitoraPontoService#confirmarLeitura(long  idInicial ,)long  idFinal )*
     */
    public void confirmarLeitura(long idInicial,long idFinal) { 
        LOG.info("Executing operation confirmarLeitura");
        System.out.println(idInicial);
        System.out.println(idFinal);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see br.udesc.ads.ponto.services.leitoraponto.LeitoraPontoService#resetarConfirmacoes(*
     */
    public void resetarConfirmacoes() { 
        LOG.info("Executing operation resetarConfirmacoes");
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see br.udesc.ads.ponto.services.leitoraponto.LeitoraPontoService#lerMarcacoes(int  quantidade )*
     */
    public java.util.List<br.udesc.ads.ponto.services.leitoraponto.RegistroMarcacao> lerMarcacoes(int quantidade) { 
        LOG.info("Executing operation lerMarcacoes");
        System.out.println(quantidade);
        try {
            java.util.List<br.udesc.ads.ponto.services.leitoraponto.RegistroMarcacao> _return = new java.util.ArrayList<br.udesc.ads.ponto.services.leitoraponto.RegistroMarcacao>();
            br.udesc.ads.ponto.services.leitoraponto.RegistroMarcacao _returnVal1 = new br.udesc.ads.ponto.services.leitoraponto.RegistroMarcacao();
            _returnVal1.setCodFuncionario(Long.valueOf(-8157444395035047684l));
            _returnVal1.setId(Long.valueOf(7092441092525414443l));
            _returnVal1.setMarcacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-06-10T19:55:09.391-03:00"));
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
