package br.udesc.ads.ponto.services.leitoraponto;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-06-10T19:55:09.407-03:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "LeitoraPontoService", 
                  wsdlLocation = "http://localhost:8080/leitora/services/LeitoraPontoServicePort?wsdl",
                  targetNamespace = "http://leitoraponto.services.ponto.ads.udesc.br/") 
public class LeitoraPontoService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://leitoraponto.services.ponto.ads.udesc.br/", "LeitoraPontoService");
    public final static QName LeitoraPontoServicePort = new QName("http://leitoraponto.services.ponto.ads.udesc.br/", "LeitoraPontoServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/leitora/services/LeitoraPontoServicePort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LeitoraPontoService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/leitora/services/LeitoraPontoServicePort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LeitoraPontoService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LeitoraPontoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LeitoraPontoService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public LeitoraPontoService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public LeitoraPontoService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public LeitoraPontoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns LeitoraPontoService
     */
    @WebEndpoint(name = "LeitoraPontoServicePort")
    public LeitoraPontoService getLeitoraPontoServicePort() {
        return super.getPort(LeitoraPontoServicePort, LeitoraPontoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LeitoraPontoService
     */
    @WebEndpoint(name = "LeitoraPontoServicePort")
    public LeitoraPontoService getLeitoraPontoServicePort(WebServiceFeature... features) {
        return super.getPort(LeitoraPontoServicePort, LeitoraPontoService.class, features);
    }

}
